### ISSUE TITLE
对 MinecraftUWP 安装状态的判断不可靠

### ISSUE THREAD

**Issue by jiesou** [xingchuanzhen/Minecraft_Memory_Bypass_GUI#4]
日志提示“请先安装 MinecraftUWP!”
![image](https://user-images.githubusercontent.com/84175239/151534258-2b599c32-b6f0-4db3-ae3f-1daf774c5a10.png)
但我的电脑上已经正确安装了 Minecraft UWP
![image](https://user-images.githubusercontent.com/84175239/151534487-6a010d98-0891-404c-b50e-33cd65b40022.png)

我猜这是因为默认情况下 C:\Program Files\WindowsApps 权限的所有者是 NT SERVICE\TrustedInstall
![image](https://user-images.githubusercontent.com/84175239/151534618-82d0a9d9-1e80-4cfe-b314-1f2378dccfdb.png)
而代码中似乎没有对这个目录做夺权
![image](https://user-images.githubusercontent.com/84175239/151535003-6a41220a-691c-4e33-8429-295e2b0b0d9e.png)

**Comment by xingchuanzhen** [comment]
是的，之前也有人反馈过这问题，部分本地账户可以列出文件夹，在线账户需要管理员身份来运行它，但是程序本身是不需要管理员权限的，我暂时没有找到合适的解决方案，我或许可以将此步骤删除

**Comment by xingchuanzhen** [comment]
我通过调用Win32 API中的NetworkIsolationEnumAppContainers函数解决了它
